apiVersion: v1
kind: Service
metadata:
  name: financial-agent-service
  namespace: financial-agent
  labels:
    app: financial-agent
spec:
  type: NodePort
  selector:
    app: financial-agent
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
    protocol: TCP
    name: mcp-server