[server]
port = 8501
address = "0.0.0.0"
headless = true
runOnSave = false
allowRunOnSave = false
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501